CREATE OR REPLACE FUNCTION generate_uid(first_name TEXT, last_name TEXT)
RETURNS TEXT AS $$
DECLARE
    first_letter CHAR;
    last_letter CHAR;
    digit1 INT;
    digit2 INT;
	new_uid TEXT;
BEGIN
    -- Take first letters and make uppercase
    first_letter := upper(substr(first_name, 1, 1));
    last_letter := upper(substr(last_name, 1, 1));
LOOP
    -- Generate two random digits
    digit1 := floor(random() * 10)::int;
    digit2 := floor(random() * 10)::int;

	-- Combine and store
	new_uid := first_letter || last_letter || digit1 || digit2;

	-- Check if it exists
	IF NOT EXISTS (SELECT 1 FROM employees WHERE emp_id = new_uid) THEN
            RETURN new_uid; -- unique, return it
        END IF;

        -- Otherwise, loop again and try new digits
    END LOOP;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE employees (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id VARCHAR(4) UNIQUE,  
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    employee_pass BYTEA NOT NULL
);

CREATE OR REPLACE FUNCTION set_emp_id()
RETURNS TRIGGER AS $$
BEGIN
    NEW.emp_id := generate_uid(NEW.first_name, NEW.last_name);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE TRIGGER emp_id_trigger
BEFORE INSERT ON employees
FOR EACH ROW
EXECUTE FUNCTION set_emp_id();